# Generated by Django 4.2 on 2023-04-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="jwt_access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="jwt_refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
